version: "3.7"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app-restful
    expose:
      - 8080
    environment:
      - APP_NAME=register_restful_api
    volumes:
      - .:/app

  #    command: python3 view.py --host=0.0.0.0



  mongodb:
     image: mongo
     ports:
      - "27017:27017"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
networks:
  default:
    driver: custom-driver-1



