version: "3.7"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app-restful
    expose:
      - 8080
    environment:
      - APP_NAME=register_restful_api
    volumes:
      - .:/app

  #    command: python3 view.py --host=0.0.0.0


  mongodb:
     image: mongo
     ports:
      - "27017:27017"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"

  redis:
    image: redis
    container_name: redis-image
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    hostname: amqp
    container_name: rabbitmq-image
    ports:
      - "5673:5672"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-container
    depends_on:
      - rabbitmq
      - flask
      - redis






